### ISSUE TITLE
Practica de conexión de bases de datos

### ISSUE THREAD

**Issue by Valentiin01** [SistemasTecTlaxiaco/conexion-de-bases-de-datos-turbanda#1]
[Practica de conexión de bases de datos.pdf](https://github.com/SistemasTecTlaxiaco/conexion-de-bases-de-datos-turbanda/files/6797856/Practica.de.conexion.de.bases.de.datos.pdf)

**Comment by Eva155** [comment]
Calificación: 20 puntos 
Calificó: Eva Aguilar Avendaño

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
